id: css/hidden-content
name: Inaccessible Hidden Content
level: major
category: accessibility
description: |
  Using display:none or visibility:hidden removes content from
  the accessibility tree, making it invisible to screen readers.
  Sometimes content should be visually hidden but still accessible.
  Techniques like negative positioning or clip-path should be used
  for screen-reader-only content.
triggers:
  file_patterns:
    - "**/*.css"
    - "**/*.scss"
    - "**/*.sass"
    - "**/*.less"
  code_patterns:
    - "display:\\s*none"
    - "visibility:\\s*hidden"
    - "font-size:\\s*0"
    - "height:\\s*0.*overflow"
checklist:
  - Is important content being hidden from screen readers?
  - Should this content be accessible but visually hidden?
  - Is display:none appropriate for this use case?
  - Could .sr-only (screen-reader-only) class be used instead?
fix: |
  For content that should be visually hidden but accessible:

  .sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }

  Use display:none only for truly hidden content.
tags:
  - accessibility
  - screen-reader
examples:
  bad: |
    .icon-label {
      display: none;
    }
    .skip-link {
      visibility: hidden;
    }
  good: |
    .sr-only {
      position: absolute;
      width: 1px;
      height: 1px;
      clip: rect(0, 0, 0, 0);
    }
    .skip-link:not(:focus) {
      position: absolute;
      left: -9999px;
    }
