id: react/large-component
name: Large Component Should Be Split
level: major
category: maintainability
description: |
  Detects components that are too large and handle too many responsibilities.
  Large components are harder to test, reuse, and maintain. They often mix
  concerns like data fetching, business logic, and presentation, making
  the code fragile and difficult to reason about.

triggers:
  file_patterns:
    - "**/*.jsx"
  code_patterns:
    - "function \\w+.*return\\s*\\("
    - "const \\w+ = \\(.*\\) =>"

checklist:
  - Does the component have more than 200-300 lines of JSX?
  - Does it manage more than 3-4 pieces of state?
  - Does it handle multiple unrelated responsibilities?
  - Could sections of the JSX be extracted into child components?
  - Does it mix data fetching, business logic, and presentation?
  - Are there multiple useEffect hooks handling unrelated side effects?

fix: |
  Split the component into smaller, focused components. Extract
  data fetching into custom hooks, move business logic into separate
  functions or hooks, and create presentational components for UI sections.

tags:
  - maintainability
  - architecture
  - components

examples:
  bad: |
    function Dashboard() {
      const [users, setUsers] = useState([]);
      const [posts, setPosts] = useState([]);
      const [analytics, setAnalytics] = useState(null);
      const [filters, setFilters] = useState({});
      const [sortBy, setSortBy] = useState('date');
      // ... 300+ lines of mixed logic and JSX
      return (
        <div>
          {/* User list section */}
          {/* Posts section */}
          {/* Analytics charts */}
          {/* Filters sidebar */}
        </div>
      );
    }
  good: |
    function Dashboard() {
      return (
        <div>
          <UserList />
          <PostsFeed />
          <AnalyticsCharts />
          <FiltersSidebar />
        </div>
      );
    }
